In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.getcwd()

'c:\\Users\\HP\\Desktop\\Machine Learning Programing with prajwal'

In [3]:
os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day25\\')

In [4]:
os.getcwd()

'C:\\Users\\HP\\Downloads\\Batch 93 Day25'

In [5]:
df1=pd.read_excel('Data Preprocessing Data File.xlsx')
print(df1)

   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [6]:
#Load independent and dependent variables to two sepearate arrays
'''x is independent variable'''
x=df1.iloc[:,0:-1].values
print(x)

[['France ' 44.0 72000.0]
 [nan 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [7]:
'''y is dependent variable'''
y=df1.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer=imputer.fit(x[:,0:1])
x[:,0:1]=imputer.transform(x[:,0:1])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [9]:
# Age - Constant
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=40)
imputer=imputer.fit(x[:,1:2])
x[:,1:2]=imputer.transform(x[:,1:2])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 40 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [10]:
# Age - Populate with mean -When there is no outlier.........Ok Prajwal 

from sklearn.impute import SimpleImputer
imputer=SimpleImputer()
imputer=imputer.fit(x[:,1:2])
x[:,1:2]=imputer.transform(x[:,1:2])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40.0 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 40.0 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [11]:
# salary - Mean
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40.0 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 40.0 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [12]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40.0 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 40.0 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [13]:
x[:,0]

array(['France ', 'France ', 'Germany ', 'Spain ', 'Germany ', 'France ',
       'Spain ', 'France ', 'Germany ', 'France '], dtype=object)

In [14]:
x

array([['France ', 44.0, 72000.0],
       ['France ', 27.0, 48000.0],
       ['Germany ', 40.0, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 40.0, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [15]:
# I want label encoding in country columns......
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
print(x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 40.0 54000.0]
 [2 39.0 62250.0]
 [1 40.0 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [16]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
ley=LabelEncoder()
y=ley.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [18]:
x

array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 40.0, 54000.0],
       [2, 39.0, 62250.0],
       [1, 40.0, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [19]:
'''
transformers : list of tuples
 |      List of (name, transformer, columns) tuples specifying the
 |      transformer objects to be applied to subsets of the data.'''
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(x)

In [20]:

help(ColumnTransformer)

Help on class ColumnTransformer in module sklearn.compose._column_transformer:

class ColumnTransformer(sklearn.base.TransformerMixin, sklearn.utils.metaestimators._BaseComposition)
 |  ColumnTransformer(transformers, *, remainder='drop', sparse_threshold=0.3, n_jobs=None, transformer_weights=None, verbose=False, verbose_feature_names_out=True)
 |  
 |  Applies transformers to columns of an array or pandas DataFrame.
 |  
 |  This estimator allows different columns or column subsets of the input
 |  to be transformed separately and the features generated by each transformer
 |  will be concatenated to form a single feature space.
 |  This is useful for heterogeneous or columnar data, to combine several
 |  feature extraction mechanisms or transformations into a single transformer.
 |  
 |  Read more in the :ref:`User Guide <column_transformer>`.
 |  
 |  .. versionadded:: 0.20
 |  
 |  Parameters
 |  ----------
 |  transformers : list of tuples
 |      List of (name, transformer, colum

In [23]:
''' transformers : list of tuples
 |      List of (name, transformer, columns) tuples specifying the
 |      transformer objects to be applied to subsets of the data.
 |  '''
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(x)

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(),[0])])
ct.fit_transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(),[0])],remainder='passthrough')
ct.fit_transform(x)

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 40.0, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 40.0, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
print(pd.DataFrame(x))

     0    1    2     3        4
0  1.0  0.0  0.0  44.0  72000.0
1  1.0  0.0  0.0  27.0  48000.0
2  0.0  1.0  0.0  40.0  54000.0
3  0.0  0.0  1.0  39.0  62250.0
4  0.0  1.0  0.0  40.0  64000.0
5  1.0  0.0  0.0  35.0  58000.0
6  0.0  0.0  1.0  39.0  52000.0
7  1.0  0.0  0.0  48.0  62250.0
8  0.0  1.0  0.0  50.0  83000.0
9  1.0  0.0  0.0  37.0  67000.0


In [28]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 40.0, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 40.0, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [32]:
from sklearn.preprocessing import StandardScaler
std_sca=StandardScaler()
x_STD=std_sca.fit_transform(x)
print(pd.DataFrame(x_STD))

     0         1    2         3         4
0  1.0 -0.654654 -0.5  0.660861  1.002707
1  1.0 -0.654654 -0.5 -2.079293 -1.465494
2 -1.0  1.527525 -0.5  0.016119 -0.848444
3 -1.0 -0.654654  2.0 -0.145067  0.000000
4 -1.0  1.527525 -0.5  0.016119  0.179973
5  1.0 -0.654654 -0.5 -0.789809 -0.437077
6 -1.0 -0.654654  2.0 -0.145067 -1.054127
7  1.0 -0.654654 -0.5  1.305603  0.000000
8 -1.0  1.527525 -0.5  1.627974  2.133965
9  1.0 -0.654654 -0.5 -0.467438  0.488498


In [34]:
from sklearn.preprocessing import Normalizer
Nm_x=Normalizer()
x_NOR=Nm_x.fit_transform(x)
print(pd.DataFrame(x_NOR))

          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000741  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000625  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0
