In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
os.getcwd()

'c:\\Users\\HP\\Desktop\\Machine Learning Programing with prajwal'

In [4]:
os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day25')

In [5]:
df1=pd.read_excel('c:\\Users\\HP\\Downloads\\Batch 93 Day25\\Data Preprocessing Data File.xlsx')
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [6]:
x=df1.iloc[:,0:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [7]:
x=df1.iloc[:,0:-1].values
x


array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [8]:
y=df1.iloc[:,-1]
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased , dtype: object

In [9]:
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [10]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [11]:
from sklearn.impute import SimpleImputer
si=SimpleImputer()
si.fit_transform(x[:,1:2])

array([[44.   ],
       [27.   ],
       [39.875],
       [39.   ],
       [39.875],
       [35.   ],
       [39.   ],
       [48.   ],
       [50.   ],
       [37.   ]])

In [12]:
help(si)

Help on SimpleImputer in module sklearn.impute._base object:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, copy=True, add_indicator=False, keep_empty_features=False)
 |  
 |  Univariate imputer for completing missing values with simple strategies.
 |  
 |  Replace missing values using a descriptive statistic (e.g. mean, median, or
 |  most frequent) along each column, or using a constant value.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan, None or pandas.NA, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      can be

In [13]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')
si.fit_transform(x[:,1:2])

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [14]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='constant')
si.fit_transform(x[:,1:2])

array([[44.0],
       [27.0],
       ['missing_value'],
       [39.0],
       ['missing_value'],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [15]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='constant',fill_value=555)
si.fit_transform(x[:,1:2]) 

array([[44.0],
       [27.0],
       [555],
       [39.0],
       [555],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [16]:
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [17]:
x[:,0:1]

array([['France '],
       [nan],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [18]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='most_frequent')
si.fit_transform(x[:,0:1])

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [19]:
x[:,0:-1]

array([['France ', 44.0],
       [nan, 27.0],
       ['Germany ', nan],
       ['Spain ', 39.0],
       ['Germany ', nan],
       ['France ', 35.0],
       ['Spain ', 39.0],
       ['France ', 48.0],
       ['Germany ', 50.0],
       ['France ', 37.0]], dtype=object)

In [20]:
x=df1.iloc[:,0:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [21]:
x=df1.iloc[:,0:1]
x

Country 
0   France 
1       NaN
2  Germany 
3    Spain 
4  Germany 
5   France 
6    Spain 
7   France 
8  Germany 
9   France